### ISSUE TITLE
`x ~ dist` is not supported if `dist` is an argument of the `@model` function 

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/RxInfer.jl#28]
When using `x ~ Normal(...)` in the model macro, the error `no method matching ~(::RandomVariable, ::Normal{Float64})`  is thrown. Ofcourse, this makes sense to us, but for outsiders this can be very confusing. 

My proposal: when its `std` parameter is fixed, implicitly convert to `MvNormalMeanPrecision`. Else throw a warning. Priors on the mean should be allowed.

**Comment by bvdmitri** [comment]
The issue turned out to be unrelated to the `Normal`, but a new warning has been implemented here anyway: https://github.com/biaslab/ReactiveMP.jl/commit/2a165350867cb769e031740b54c4be42984099fc

The real issue is that `RxInfer` does not understand `x ~ prior` syntax, but its going to be fixed in #31 too.
