### ISSUE TITLE
Inference using a DataArray

### ISSUE THREAD

**Issue by Dhuige** [biaslab/RxInfer.jl#50]
It might be nice to infer data using an array. Slicing the array into a vector in the model able to read it out

By which I mean that one would be able to use an array given the following:

![image](https://user-images.githubusercontent.com/31347265/213677251-5b8ce74e-5150-4efe-9b51-c9d63edd555f.png)

**Comment by albertpod** [comment]
Hi @Dhuige,

Thanks for trying out `RxInfer.jl`. Can you be more specific about the nature of the issue?
The model you've provided is incomplete and has unused variables, e.g. `y` and `tau`

In order to create a multivariate input, you should use the following `datavar` specification.
```julia
Data_Array = datavar(Vector{Float64}, N)
```
You can't use `dot` with a vector of datavars of type `Float64`. It must be instead a single datavar of type `Vector{Float64}`, e.g. 
```julia
Data_Array_Univariate = datavar(Float64, N)
Data_Array_Multivariate = datavar(Vector{Float64}, N)
for i in 1:N
    Data_Array_Univariate[i] ~ dot(Data_Array_Multivariate[i], theta) + epsilon
end
```
We will be happy to help further if you provide more details on what you are trying to achieve with this model.

**Comment by Dhuige** [comment]
Thank you for the improvement on my code used, what I am trying to say is that it would be nice if one could use 1 Array as input and output. In this example, this would imply that a slice of the multivariate is treated as Data_Array_Univariate. 

in other words:
Data_Array_Univariate = datavar(Float64, N)
Data_Array_Multivariate = datavar(Vector{Float64}, N)
for i in 1:N
    Data_Array_Multivariate[:,1][i] ~ dot(Data_Array_Multivariate[i], theta) + epsilon
end


Preferably, the dot product would also work if the Data_Array_Multivariate is sliced in an array (since it will make mathematical sense, thus convenient to use).

**Comment by albertpod** [comment]
I see @Dhuige. Thanks for raising the issue. 
This type of model definition isn't supported yet.
