### ISSUE TITLE
The nonlinear sensor fusion demo is broken

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/RxInfer.jl#52]
The inference is broken in the example https://biaslab.github.io/RxInfer.jl/stable/examples/Nonlinear%20Sensor%20Fusion/

Check the plots with the inference results

**Comment by Nimrais** [comment]
@bvdmitri @albertpod

I am near to fixing it. There is a super stupid one (to remove the optional check on the proper messages and the plots will be correct). But It's possible to fix it by tuning with CVI hyperparameters: also, I think it's valuable because we will have a clear example to the user that hyperparameters are important.

I expect to end it to 24.02.2023.

**Comment by albertpod** [comment]
Please update the end date of this fix ;)

**Comment by Nimrais** [comment]
@albertpod I will end the fix at 06.02.2023.

**Comment by Nimrais** [comment]
@albertpod Sure, I meant March not February.
