### ISSUE TITLE
Nice docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [biaslab/RxInfer.jl#54]
How did you get documenter to give you that nice navigation bar across the top?

**Comment by bvdmitri** [comment]
Hey, thanks! 

We hacked it around really, because `Documenter.jl` does not allow you to do that (yet?). We implemented our own simple solution here:
https://github.com/biaslab/RxInfer.jl/blob/main/docs/src/assets/header.js
https://github.com/biaslab/RxInfer.jl/blob/main/docs/src/assets/header.css
https://github.com/biaslab/RxInfer.jl/blob/main/docs/src/assets/theme.css

Long story short it simply injects a few HTML nodes at webpage initialisation using pure javascript (and it could potentially break with a new release of Documenter.jl in case of layout changes)

Can I close the issue?

**Comment by ChrisRackauckas** [comment]
Awesome, thanks for the info.
