### ISSUE TITLE
"Edit on GitHub" button on example pages are broken

### ISSUE THREAD

**Issue by wouterwln** [biaslab/RxInfer.jl#70]
For example, on https://biaslab.github.io/RxInfer.jl/stable/examples/Active%20Inference%20Mountain%20car/ the link at the top refers to https://github.com/biaslab/RxInfer.jl/blob/main/docs/src/examples/Active%20Inference%20Mountain%20car.md#, which is nonexistent. 

The link seems to refer a .md file, whereas I can only find the .ipynb files in /main/examples. If the link should be redirected to /main/examples instead of /main/docs/src/examples, I can probably do that quickly.

**Comment by bvdmitri** [comment]
Hm, good find! The reason is that the documentation build first converts Jupyter notebooks to `.md` files and then composes the website. Those `.md` files exist only during the build stage and are not present in the repository. I think we should either disable that button in the examples page or redirect it somehow to the corresponding notebook.
