### ISSUE TITLE
`make_node(f::Function)` is broken if all input `args` are DataVariable

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/RxInfer.jl#9]
Current implementation returns an actual result of `f(args)`, it should be `PointMass` at least. Also would be nice to implement `args::Union{ConstVariable, DataVariable}...`

**Comment by bvdmitri** [comment]
@albertpod This might have been fixed in RxInfer.jl 2.0. I'll leave it open until we release.

**Comment by bvdmitri** [comment]
https://discourse.julialang.org/t/reactivemp-hierarchical-linear-regression/88112

**Comment by wmkouw** [comment]
I started work on this. You mentioned it might have already been fixed in `>= 2.0` and `make_node(+, datavar(:x, Float64), datavar(:y, Float64), datavar(:z, Float64))` seems to work fine. Is that correct, Dmitry? 

Or does `f::Function` refer to the nonlinear function in the delta node?

**Comment by wmkouw** [comment]
Small status update: successfully constructed the proxy datavar inside model creation (see branch `9-makenode-alldatavars` [tests](https://github.com/biaslab/RxInfer.jl/blob/9-makenode-alldatavars/test/models/datavars/test_fn_datavars.jl)). It still errors during inference because it tries to apply `fform` to a `Tuple{Pointmass{Float64}, Pointmass{Float64}}`

Notes:
- I extended the ReactiveMP method `isproxy` inside `inference.jl`. This should be removed and pushed to ReactiveMP later ([line](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/variables/data.jl#L95)). I've added it here for ease of testing.
- I used `ReactiveMP._getmarginal.(args)...` instead of `ReactiveMP._getmarginal(args, IncludeAll())` since it doesn't iterate over the vararg collection. But I might be misinterpreting the use of `IncludeAll()`.
- Choice for `combineLatest(.., strategy = PushNew())` over `zipped` was discussed with Dmitry.
- There is currently no `getrecent` for a datavar with a ProxyObservable. You can call its proxy_sources but that just gives you the tuple of recent source messages. I assume we will want a `getrecent` method that performs the mapping?

**Comment by bvdmitri** [comment]
Thanks for working on this @wmkouw !

> This should be removed and pushed to ReactiveMP later ([line](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/variables/data.jl#L95)). I've added it here for ease of testing.

Yes! I think it can wait for now.

> It still errors during inference because it tries to apply fform to a Tuple{Pointmass{Float64}, Pointmass{Float64}}

Perhaps you can use the [`ReactiveMP.getpointmass`](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/distributions/pointmass.jl#L21) to get the actual value (In the same way we now use `ReactiveMP.getdata` to remove the `Marginal{...}` wrapper).

E.g.
```
(d) -> fform(ReactiveMP.getpointmass.(ReactiveMP.getdata.(d))...)
```

> I used ReactiveMP._getmarginal.(args)... instead of ReactiveMP._getmarginal(args, IncludeAll()) since it doesn't iterate over the vararg collection. But I might be misinterpreting the use of IncludeAll().

I think we can leave it for now and fix this later. `_getmarginal` does not iterate over var-arg collection either, `_getmarginal.` does. However, `_getmarginal` is an internal function that may change, the more stable API for getting the marginal is `getmarginal` (without underscore in the beggining). `getmarginal` accepts two arguments. The second can be either `SkipClamped()`, `SkipInitial()` or `IncludeAll()`, which indicates if you are interesting in all marginals or maybe you want to skip e.g. initial ones. By default if you simply call the `getmarginal(variable)` the strategy is `SkipInitial()`, because users are usually not interested in the initial values set with `initmarginals = ...`. 

You could use
```julia
getmarginal.(args, IncludeAll())
```
but now I also realised that this will not work unless you define the `Base.broadcastable(::IncludeAll) = Ref(IncludeAll())`, e.g. like [here](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/variables/variable.jl#L13). 

> There is currently no getrecent for a datavar with a ProxyObservable. You can call its proxy_sources but that just gives you the tuple of recent source messages. I assume we will want a getrecent method that performs the mapping?

Does the implementation call the `getrecent` now for something? Ideally, I would want to get rid of the `getrecent` in the future. It's an optimization hack, but it is indeed needed sometimes. The relevant piece of code for datavars is [here](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/variables/data.jl#L160). Now it assumes that datavar has the `Subject` as its source, but now we extend it to `combine(Subjects...) + map`. I can write the new method for the `getrecent`.

**Comment by wmkouw** [comment]
> Perhaps you can use the [ReactiveMP.getpointmass](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/distributions/pointmass.jl#L21) to get the actual value

I should have provided a bit more information. The current datavar construction works. For instance, if you set up:
```julia
fform(x,y) = x+y
x = datavar(:x, Float64)
y = datavar(:y, Float64)
z = combineLatest(ReactiveMP._getmarginal.((x,y))..., strategy=PushNew()) |> map(Any, (d) -> fform(ReactiveMP.getdata(d)...))
f = ReactiveMP.datavar(ReactiveMP.DataVariableCreationOptions(z), :f, Any)
subscribe!(f.messageout, logger())
```
and then update `x` and `y` with `1.0` and `2,0` respectively, you'll get
```julia
[LogActor] Data: 3.0
```
So, updating `x` and `y` with `Message{Float64}`'s, updates the `Message{Float64}` of the new datavar. But during inference, the `Message{Float64}` seem to be replaced with `PointMass{Float64}`, as indicated by the stacktrace:
```julia
ERROR: MethodError: no method matching +(::PointMass{Float64}, ::PointMass{Float64})
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  +(::ChainRulesCore.Tangent{P}, ::P) where P at ~/.julia/packages/ChainRulesCore/a4mIA/src/tangent_arithmetic.jl:146
  +(::VectorizationBase.CartesianVIndex, ::Any) at ~/.julia/packages/VectorizationBase/G9NJI/src/cartesianvindex.jl:80
  ...
Stacktrace:
  [1] (::RxInfer.var"#105#106"{typeof(+)})(d::Tuple{Marginal{PointMass{Float64}, Nothing}, Marginal{PointMass{Float64}, Nothing}})
```
I am currently trying to figuring out where exactly `x` and `y` are given PointMass distributions. Adding the `getpointmass` where you indicated won't work since `getdata` returns Floats. But it should be probably be added somewhere in the `map`.

Thanks for the information on `getmarginal`. I will add the broadcastable and then switch to include the strategy. 

As for `getrecent`, I don't think it is currently used. I saw that it is only defined for `Subject`s and the extension indeed seems straightforward. I can add it if you want, but I can also leave it if you have future plans for `getrecent` anyway?

**Comment by wmkouw** [comment]
Extending `getpointmass` with `ReactiveMP.getpointmass(point::Float64) = point` allows construction of datavars of type `PointMass{Float64}`. So, the following
```julia
fform(x,y) = x+y
x = datavar(:x, PointMass{Float64})
y = datavar(:y, PointMass{Float64})
z = combineLatest(ReactiveMP._getmarginal.((x,y))..., strategy=PushNew()) |> map(Any, (d) -> fform(ReactiveMP.getpointmass.(ReactiveMP.getdata(d))...))
f = ReactiveMP.datavar(ReactiveMP.DataVariableCreationOptions(z), :f, Any)
subscribe!(f.messageout, logger())
```
will generate `[LogActor] Data: 3.0` upon updating `x` and `y` as before. 

However, during inference (with `datavar(.., Float64)`) I run into:
```julia
  MethodError: no method matching as_marginal(::Float64)
  Closest candidates are:
    as_marginal(::ReactiveMP.Marginal) at ~/.julia/dev/ReactiveMP/src/marginal.jl:99
    as_marginal(::ReactiveMP.Message) at ~/.julia/dev/ReactiveMP/src/ReactiveMP.jl:53
  Stacktrace:
    [1] on_next!(actor::Rocket.MapActor{Any, Rocket.CombineLatestUpdatesInnerActor{ReactiveMP.Marginal, R
```
So, this has some unexpected side-effects.

**Comment by bvdmitri** [comment]
@wmkouw I think that happens because the modified streams sends actual values of type `Float64` (in this example), but it should send a `Message`. Look at the line `src/variables/data.jl:117` in `ReactiveMP.jl`. I think we solution here it so simply wrap the result of the `fform(...)` into `Message`.

`Message` takes 4 arguments.

- data
- is_clamped (put `false`)
- is_initial (put `false`)
- addons (put `nothing`)

**Comment by wmkouw** [comment]
Thanks, Dmitry. That did the trick. 

Ok. So, to summarize:
- In RxInfer, I have added a `make_node` with `args::Vararg{<:ReactiveMP.DataVariable}` and unit tests for applying functions of the form `f(x,y, ...)` to datavars `x,y,..`.
- In ReactiveMP, I have added `broadcastable()` methods for each of the `MarginalSkipStrategy()`'s, a `getpointmass` method for `Float64` args, modified the `isproxy` method for datavariables to check for a `proxy` field, and fixed some typos in docstrings.
- In Rocket, I have added a `getrecent` method for `ProxyObservable`'s and a `getrecent` for `CombineLatestObservable` types (turned out to be necessary). 

Shall I send 3 PR's linking to this issue?
